name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --no-cache-dir -r notebooks/requirements.txt
        python -m pip list

    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build notebooks

    - name: Compile LaTeX
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          cd syllabus && \
          latexmk && \
          cd ../homeworks/homework_1 && \
          pdflatex homework_1 && \
          cd ../homework_2 && \
          pdflatex homework_2"

    - name: Copy syllabus for deployment
      run: |
        cp syllabus/syllabus.pdf notebooks/_build/html/syllabus.pdf && \
        cp homeworks/homework_1/homework_1.pdf notebooks/_build/html/homework_1.pdf && \
        cp homeworks/homework_2/homework_2.pdf notebooks/_build/html/homework_2.pdf

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: notebooks/_build/html
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
